const BMCKey = {
    keyActivities: {
      name: 'keyActivities',
      englishLabel: 'Key Activities',
      germanLabel: 'Kernaktivitäten',
      component: 'textArea',
      englishTooltip: 'Describe the key activities including processes and operations that you perform to deliver your value proposition',
      germanTooltip: 'Welche Kernaktivitäten wie Operationen und Prozesse führen Sie aus, um Wert für ihre Kunden zu schaffen?',
      validations: '300',
      labelClassName: 'profile-label',
      valueClassName: 'profile-value',
      type: 'textArea',
      typeValues: null
    },
    keyResources: {
      name: 'keyResources',
      englishLabel: 'Key Resources',
      germanLabel: 'Wichtigste Ressourcen',
      component: 'textArea',
      englishTooltip: 'Describe the key resources including technologies, knowledge, human and material resources that you make use of in your operations',
      germanTooltip: 'Beschreiben Sie die wichtigsten Technologien, Materiellen & Humanen Ressourcen, und Wissen, das das Unternehmen besitzt',
      validations: '300',
      labelClassName: 'profile-label',
      valueClassName: 'profile-value',
      type: 'textArea',
      typeValues: null
    },
    keyPartnership: {
      name: 'keyPartnership',
      englishLabel: 'Key Partnership',
      germanLabel: 'Wichtigste Partnerschaften',
      component: 'textArea',
      englishTooltip: 'Describe the most important types of partnerships, which perform key activities and provide key resources to your business',
      germanTooltip: 'Beschreiben Sie die wichtigsten Partnerschaften, die ihren Unternehmenserfolg unterstützen',
      validations: '300',
      labelClassName: 'profile-label',
      valueClassName: 'profile-value',
      type: 'textArea',
      typeValues: null
   },
    costStructure: {
      name: 'costStructure',
      englishLabel: 'Cost Structure',
      germanLabel: 'Kostenstruktur',
      component: 'textArea',
      englishTooltip: 'Highlight the biggest cost factors that you incure during your operations',
      germanTooltip: 'Was sind die größten Kostenbereiche in ihrem Geschäft?',
      validations: '300',
      labelClassName: 'profile-label',
      valueClassName: 'profile-value',
      type: 'textArea',
      typeValues: null
   },
   valueProposition: {
     name: 'valueProposition',
     englishLabel: 'Value Proposition',
     germanLabel: 'Werteproposition',
     placeholder: 'Value Proposition',
     component: 'textArea',
     englishTooltip: 'Specify your value proposition, that is, the key benefits that you provide to your customers',
     germanTooltip: 'Was ist der Wert und die Leistung, die Sie für Ihre Kunden erbringen?',
     validations: '300',
     labelClassName: 'profile-label',
     valueClassName: 'profile-value',
     type: 'textArea',
     typeValues: null
   },
   customerRelationships: {
     name: 'customerRelationships',
     englishLabel: 'Customer Relationships',
     germanLabel: 'Kundenbeziehungen',
     component: 'textArea',
     englishTooltip: 'Describe your customer relationships',
     germanTooltip: 'Beschreiben Sie die Art der Kundenbeziehungen, die Sie pflegen',
     validations: '300',
     labelClassName: 'profile-label',
     valueClassName: 'profile-value',
     type: 'textArea',
     typeValues: null
   },
   customerSegments: {
     name: 'customerSegments',
     englishLabel: 'Customer Segments',
     germanLabel: 'Kundensegmente',
     component: 'multiSelect',
     englishTooltip: 'Describe your most important customer segments',
     germanTooltip: 'Beschreiben Sie ihre wichtigsten Kundensegmente',
     validations: '300',
     labelClassName: 'profile-label',
     valueClassName: 'profile-value',
     type: 'multiSelect',
     typeValues: null
   },
   channels: {
     name: 'channels',
     englishLabel: 'Channels',
     germanLabel: 'Kanäle',
     component: 'multiSelect',
     englishTooltip: 'Describe the channels you use to reach your customers',
     germanTooltip: 'Durch welche Kanäle (online und offline) erreichen Sie Ihre Kunden?',
     validations: '300',
     labelClassName: 'profile-label',
     valueClassName: 'profile-value',
     type: 'multiSelect',
     typeValues: null
   },
   revenueStreams: {
     name: 'revenueStreams',
     englishLabel: 'Revenue Streams',
     germanLabel: 'Umsatzmodelle',
     component: 'multiSelect',
     englishTooltip: 'Describe the most important revenue streams, which you use to monetize your business',
     germanTooltip: 'Durch welche Kanäle (online und offline) erreichen Sie Ihre Kunden?',
     validations: '300',
     labelClassName: 'profile-label',
     valueClassName: 'profile-value',
     type: 'multiSelect',
     typeValues: null
   },
   technologies: {
     name: 'technologies',
     englishLabel: 'Technolgies',
     germanLabel: 'Technologien',
     component: 'multiSelect',
     englishTooltip: 'Describe the most important technologies used in your operations',
     germanTooltip: 'Benennen Sie die wichtigsten Technologien, die Sie verwenden',
     validations: '',
     labelClassName: 'profile-label',
     valueClassName: 'profile-value',
     type: 'multiSelect',
     typeValues: null
   },
   standardsCertifications: {
     name: 'standardsCertifications',
     englishLabel: 'Standards & Certifications',
     germanLabel: 'Standards & Zertifizierungen',
     component: 'multiSelect',
     englishTooltip: 'Describe the most important standards (e.g. DIN, ISO) followed in your operations',
     germanTooltip: 'Beschreiben Sie die wichtigsten Standards und Zertifizierungen, denen Sie folgen, bzw. die Sie erhalten haben.',
     validations: '',
     labelClassName: 'profile-label',
     valueClassName: 'profile-value',
     type: 'multiSelect',
     typeValues: null
   }
};

export default BMCKey;
