const ContactDetails = {
    companyWebsite: {
      name: 'companyWebsite',
      englishLabel: 'Company Website',
      germanLabel: 'Webseite',
      component: 'text',
      englishTooltip: 'n/a',
      germanTooltip: 'n/a',
      validations: '',
      clickable: 'yes',
      labelClassName: 'profile-label',
      valueClassName: 'profile-value',
      type: 'string',
      typeValues: null
    },
    phone: {
      name: 'phone',
      englishLabel: 'Phone',
      germanLabel: 'Telefon',
      component: 'phoneNumber',
      englishTooltip: 'n/a',
      germanTooltip: 'n/a',
      validations: '',
      labelClassName: 'profile-label',
      valueClassName: 'profile-value',
      type: 'phone',
      typeValues: null
    },
    companyEmail: {
      name: 'companyEmail',
      englishLabel: 'E-mail',
      germanLabel: 'E-mail',
      component: 'text',
      englishTooltip: 'n/a',
      germanTooltip: 'n/a',
      validations: '',
      mailTo: 'yes',
      labelClassName: 'profile-label',
      valueClassName: 'profile-value',
      type: 'string',
      typeValues: null
    },
    skype: {
      name: 'skype',
      englishLabel: 'Skype',
      germanLabel: 'Skype',
      component: 'text',
      englishTooltip: 'n/a',
      germanTooltip: 'n/a',
      validations: '50',
      clickable: 'yes',
      labelClassName: 'profile-label',
      valueClassName: 'profile-value',
      type: 'skype',
      typeValues: null
    },
    facebook: {
      name: 'facebook',
      englishLabel: 'Facebook',
      germanLabel: 'Facebook',
      component: 'text',
      englishTooltip: 'n/a',
      germanTooltip: 'n/a',
      validations: '',
      clickable: 'yes',
      labelClassName: 'profile-label',
      valueClassName: 'profile-value',
      type: 'facebook',
      typeValues: null
    },
    linkedIn: {
      name: 'linkedIn',
      englishLabel: 'LinkedIn',
      germanLabel: 'LinkedIn',
      component: 'text',
      englishTooltip: 'n/a',
      germanTooltip: 'n/a',
      validations: '',
      clickable: 'yes',
      labelClassName: 'profile-label',
      valueClassName: 'profile-value',
      type: 'linkedIn',
      typeValues: null
    },
    twitter: {
      name: 'twitter',
      englishLabel: 'Twitter',
      germanLabel: 'Twitter',
      component: 'text',
      englishTooltip: 'n/a',
      germanTooltip: 'n/a',
      validations: '',
      clickable: 'yes',
      labelClassName: 'profile-label',
      valueClassName: 'profile-value',
      type: 'twitter',
      typeValues: null
    }
};

export default ContactDetails;
