import {multiSelectValues, chunk} from '../../util/multiSelectValues';

export function OrgaBizLegal(values) {
return {
   organizationType: {
      name: 'organizationType',
      englishLabel: 'Organization Type',
      germanLabel: 'Organisationsform',
      component: 'dropdown',
      englishTooltip: 'Chose what type of organisation you are',
      germanTooltip: 'Wählen Sie aus, welcher Organisationsform sie angehören',
      validations: '',
      labelClassName: 'profile-label',
      valueClassName: 'profile-value',
      type: 'dropdown',
      typeValues: values.cmsData && values.cmsData.organization_type.split('\n')
    },
    businessType: {
      name: 'businessType',
      englishLabel: 'Business Type',
      germanLabel: 'Geschäftsart',
      placeholder: 'Business Type',
      component: 'dropdownMultiple',
      englishTooltip: 'Chose the operational business model that your organisation follows',
      germanTooltip: 'Wählen Sie die Geschäftsart ihres Unternehmens',
      validations: '',
      labelClassName: 'profile-label',
      valueClassName: 'profile-value',
      type: 'dropdownMultiple',
      typeValues: values.cmsData && multiSelectValues(chunk(values.cmsData.business_type.split('\n')))
    },
    legalForm: {
      name: 'legalForm',
      englishLabel: 'Legal Form',
      germanLabel: 'Geschäftsform',
      component: 'text',
      englishTooltip: 'Specify the legal form of registration of your  business',
      germanTooltip: 'Wählen Sie die rechtliche Geschäftsform Ihres Unternehmens',
      validations: '',
      labelClassName: 'profile-label',
      valueClassName: 'profile-value',
      type: 'string',
      typeValues: null
    },
    industry: {
     name: 'industry',
     englishLabel: 'Industry',
     germanLabel: 'Industrie',
     component: 'dropdown',
     englishTooltip: 'Select your industry according to SIC classification',
     germanTooltip: 'Wählen Sie ihre Industrie (nach SIC Klassifizierung)',
     validations: '',
     labelClassName: 'profile-label',
     valueClassName: 'profile-value',
     type: 'dropdown',
     typeValues: values.cmsData && values.cmsData.industry.split('\n')
    },
    sector: {
      name: 'sector',
      englishLabel: 'Sector',
      germanLabel: 'Sektor',
      component: 'dropdownspecial',
      englishTooltip: 'Select your sector according to SIC classification',
      germanTooltip: 'Wählen Sie ihren Sektor (nach SIC Klassifizierung)',
      validations: '',
      labelClassName: 'profile-label',
      valueClassName: 'profile-value',
      type: 'dropdown',
      typeValues: values.cmsData && values.cmsData.sector.split('\n'),
      conditionalValues: {
        Energy: ['Energy Equipment & Services', 'Oil, Gas & Consumable Fuels'],
        Materials: ['Chemicals', 'Construction Materials', 'Containers & Packaging', 'Metals & Mining', 'Paper and Forest Products'],
        Industrials: ['Aerospace & Defense', 'Building Products', 'Construction & Engineering', 'Electrical Equipment', 'Industrial Conglomerates', 'Machinery', 'Commercial Services & Supplies', 'Professional Services', 'Transportation'],
        'Automobiles & Components': ['Auto Components', 'Automobiles'],
        'Consumer Durables & Apparel': ['Household Durables', 'Leisure Products', 'Textiles, Apparel & Luxury Goods'],
        'Consumer Services': ['Hotels, Restaurants & Leisure', 'Diversified Consumer Services', 'Media', 'Retailing'],
        'Consumer Staples': ['Food & Staples Retailing', 'Beverages', 'Food Products', 'Tobacco', 'Household & Personal Products'],
        'Health Care': ['Health Care Equipment & Supplies', 'Health Care Technology', 'Biotechnology', 'Pharmaceuticals', 'Life Sciences'],
        Financials: ['Banks', 'Thrifts & Mortgage Finance', 'Diversified Financial Services', 'Consumer Finance', 'Capital Markets', 'Insurance'],
        'Information Technology': ['Internet Software & Services', 'IT Services', 'Software', 'Technology Hardware & Equipment', 'Electronic Equipment, Instruments & Components', 'Office Electronics', 'Semiconductor Equipment & Products', 'Internet of Things'],
        'Telecommunication Services': ['Diversified Telecommunication Services'],
        Utilities: ['Electric Utilities', 'Gas Utilities', 'Multi-Utilities', 'Water Utilities', 'Independent Power and Renewable Electricity Producers'],
        'Real Estate': ['Equity Real Estate Investment Trusts (REITs)', 'Real Estate Management & Development']
      }
    },
    subSector: {
      name: 'subSector',
      englishLabel: 'Sub-Sector',
      germanLabel: 'Sub-Sektor',
      component: 'dropdownspecial',
      englishTooltip: 'Select your sector according to SIC classification',
      germanTooltip: 'Wählen Sie ihren Sub-Sektor (nach SIC Klassifizierung)',
      validations: '',
      labelClassName: 'profile-label',
      valueClassName: 'profile-value',
      type: 'dropdownMultiple',
      typeValues: values.cmsData && multiSelectValues(chunk(values.cmsData.sub_sector.split('\n'))),
      conditionalValues: {
        'Energy Equipment & Services': ['Oil & Gas Drilling', 'Oil & Gas Equipment & Services'],
        'Oil, Gas & Consumable Fuels': ['Integrated Oil & Gas', 'Oil & Gas Exploration & Production', 'Oil & Gas Refining & Marketing', 'Oil & Gas Storage & Transportation', 'Coal & Consumable Fuels'],
        Chemicals: ['Commodity Chemicals', 'Diversified Chemicals', 'Fertilizers & Agricultural Chemicals', 'Industrial Gases', 'Specialty Chemicals'],
        'Construction Materials': [],
        'Containers & Packaging': ['Metal & Glass Containers', 'Paper Packaging'],
        'Metals & Mining': ['Aluminum', 'Diversified Metals & Mining', 'Gold', 'Precious Metals & Minerals', 'Silver', 'Steel'],
        'Paper and Forest Products': ['Forest Products', 'Paper Products'],
        'Aerospace & Defense': [],
        'Building Products': [],
        'Construction & Engineering': [],
        'Electrical Equipment': ['Electrical Components & Equipment', 'Heavy Electrical Equipment'],
        'Industrial Conglomerates': [],
        Machinery: ['Construction Machinery & Heavy Trucks', 'Agricultural & Farm Machinery', 'Industrial Machinery'],
        'Commercial Services & Supplies': ['Commercial Printing', 'Data Processing Services', 'Diversified Commercial & Professional Services', 'Environmental & Facilities Services', 'Office Services & Supplies', 'Diversified Support Services', 'Security & Alarm Services'],
        'Professional Services': ['Human Resource & Employment Services', 'Research & Consulting Services'],
        Transportation: ['Air Freight & Logistics', 'Airlines', 'Marine', 'Road & Rail', 'Transportation Infrastructure'],
        'Auto Components': ['Auto Parts & Equipment', 'Tires & Rubber'],
        Automobiles: ['Automobile Manufacturers', 'Motorcycle Manufacturers'],
        'Household Durables': ['Consumer Electronics', 'Home Furnishings', 'Homebuilding', 'Household Appliances', 'Housewares & Specialties'],
        'Leisure Products': [],
        'Textiles, Apparel & Luxury Goods': ['Apparel, Accessories & Luxury Goods', 'Footwear', 'Textiles'],
        'Hotels, Restaurants & Leisure': ['Casinos & Gaming', 'Hotels, Resorts & Cruise Lines', 'Leisure Facilities', 'Restaurants'],
        'Diversified Consumer Services': ['Education Services', 'Specialized Consumer Services'],
        Media: ['Advertising', 'Broadcasting', 'Cable & Satellite', 'Movies & Entertainment', 'Publishing'],
        Retailing: ['Catalog Retail', 'Internet Retail', 'Department Stores', 'General Merchandise Stores', 'Apparel Retail', 'Computer & Electronics Retail', 'Home Improvement Retail', 'Specialty Stores', 'Automotive Retail', 'Homefurnishing Retail'],
        'Food & Staples Retailing': ['Drug Retail', 'Food Distributors', 'Food Retail', 'Hypermarkets & Super Centers'],
        Beverages: ['Brewers', 'Distillers & Vintners', 'Soft Drinks'],
        'Food Products': ['Agricultural Products', 'Meat, Poultry & Fish', 'Packaged Foods & Meats'],
        Tobacco: [],
        'Household & Personal Products': ['Household Products', 'Personal Products'],
        'Health Care Equipment & Supplies': ['Health Care Equipment', 'Health Care Supplies', 'Health Care Distributors', 'Health Care Services', 'Health Care Facilities', 'Managed Health Care'],
        'Health Care Technology': [],
        Biotechnology: [],
        Pharmaceuticals: [],
        'Life Sciences': [],
        Banks: ['Diversified Banks', 'Regional Banks'],
        'Thrifts & Mortgage Finance': ['Thrifts & Mortgage Finance'],
        'Diversified Financial Services': ['Consumer Finance', 'Other Diversified Financial Services', 'Multi-Sector Holdings', 'Specialized Finance'],
        'Consumer Finance': [],
        'Capital Markets': ['Asset Management & Custody Banks', 'Investment Banking & Brokerage', 'Diversified Capital Markets'],
        Insurance: ['Insurance Brokers', 'Life & Health Insurance', 'Multi-line Insurance', 'Property & Casualty Insurance', 'Reinsurance'],
        'Internet Software & Services': [],
        'IT Services': ['IT Consulting & Other Services', 'Data Processing & Outsourced Services'],
        Software: ['Application Software', 'Systems Software', 'Home Entertainment Software'],
        'Technology Hardware & Equipment': ['Communications Equipment', 'Networking Equipment', 'Telecommunications Equipment', 'Computer Hardware', 'Computer Storage & Peripherals', 'Technology Hardware, Storage & Peripherals'],
        'Electronic Equipment, Instruments & Components': ['Electronic Equipment & Instruments', 'Electronic Components', 'Electronic Manufacturing Services', 'Technology Distributors'],
        'Office Electronics': ['Office Electronics'],
        'Semiconductor Equipment & Products': ['Semiconductor Equipment', 'Semiconductors'],
        'Internet of Things': ['Internet of Things'],
        'Diversified Telecommunication Services': ['Alternative Carriers', 'Integrated Telecommunication Services'],
        'Wireless Telecommunication Services': [],
        'Electric Utilities': [],
        'Gas Utilities': [],
        'Multi-Utilities': [],
        'Water Utilities': [],
        'Independent Power and Renewable Electricity Producers': ['Independent Power Producers & Energy Traders', 'Renewable Electricity'],
        'Equity Real Estate Investment Trusts (REITs)': ['Industrial REITs', 'Hotel & Resort REITs', 'Office REITs', 'Health Care REITs', 'Residential REITs', 'Retail REITs', 'Specialized REITs'],
        'Real Estate Management & Development': ['Diversified Real Estate Activities', 'Real Estate Operating Companies', 'Real Estate Development', 'Real Estate Services']
      }
    }
};
}
