import {multiSelectValues, chunk} from '../../util/multiSelectValues';

/*
* Sub-Sections
* productService
* applicationDomain
* valuePrice
* operationDetails
*/

export function ProductServices(values) {
return {
    productService: {
      productName: {
       name: 'productName',
       englishLabel: 'Product Name',
       germanLabel: 'Produkt Name',
       component: 'text',
       englishTooltip: 'Indicate the name of your product or service. If you do not have a name, a short descriptive title can substitute',
       germanTooltip: 'Fügen Sie den Namen oder einen kurzen, beschreibenden Titel für Ihr Produkt hinzu',
       validations: '25',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'string',
       typeValues: null
     },
     productClass: {
       name: 'productClass',
       englishLabel: 'Product Class',
       germanLabel: 'Produktklasse',
       component: 'dropdownMultiple',
       englishTooltip: 'Choose the product categories that your product/service belongs to',
       germanToooltip: 'Wählen Sie die Produktklasse, unter die Ihr Produkt fällt',
       validations: '30',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'dropdownMultiple',
       typeValues: values && values.cmsData && multiSelectValues(chunk(values.cmsData.product_class.split('\n')))
     },
     productCoreTechnologies: {
      name: 'productCoreTechnologies',
      englishLabel: 'Core Technologies',
      germanLabel: 'Technologiebereiche',
      component: 'dropdownMultiple',
      englishTooltip: '',
      germanTooltip: '',
      validations: '',
      labelClassName: 'profile-label',
      valueClassName: 'profile-value',
      type: 'dropdownMultiple',
      typeValues: values && values.cmsData && multiSelectValues(chunk(values.cmsData.core_technologies.split('\n')))
     },
     technologyField: {
       name: 'technologyField',
       englishLabel: 'Technology Field',
       germanLabel: 'Technologie-Feld',
       component: 'multiSelectAutoSuggest',
       englishTooltip: 'Indicate the technology field that your product/service belongs to',
       germanTooltip: 'Welchem Technologiebereich gehört Ihre Lösung an? (z.B. FInTech, Internet of Things, ...)',
       validations: '',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'multiSelectAutoSuggest',
       typeValues: values && values.cmsData && multiSelectValues(chunk(values.cmsData.technology_application_field.split('\n')))
     },
     productCategory: {
       name: 'productCategory',
       englishLabel: 'Product Category',
       germanLabel: 'Produktkategorie',
       component: 'multiSelect',
       englishTooltip: 'Indicate the product category that your product belongs to',
       germanTooltip: 'Wählen Sie die Produktkategorie(n), zu denen Ihr Produkt zählt',
       validations: '50',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'multiSelect',
       typeValues: null
     },
     productSolution: {
       name: 'productSolution',
       englishLabel: 'Product Solution',
       germanLabel: 'Lösungsansatz im Detail',
       component: 'textArea',
       englishTooltip: 'Give a short description of the solution your product provides',
       germanTooltip: 'Beschreiben Sie Ihre Lösung im Detail',
       validations: '150',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'textArea',
       typeValues: null
     },
     businessObjective: {
       name: 'businessObjective',
       englishLabel: 'Solves Business Objective',
       germanLabel: 'Geschäftsziel',
       component: 'dropdownMultiple',
       englishTooltip: 'Chose tags which broadly describe the business objectives that your product/service is improving',
       germanTooltip: 'Welche Geschäftsziele unterstützt Ihre Lösung im Endeffekt?',
       validations: '',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'dropdownMultiple',
       typeValues: values && values.cmsData && multiSelectValues(chunk(values.cmsData.business_objectives.split('\n')))
     }
   }, /* Product Service END */
   applicationDomain: {
     problemSolved: {
        name: 'problemSolved',
        englishLabel: 'Problem Solved',
        germanLabel: 'Problembeschreibung',
        component: 'textArea',
        englishTooltip: 'Give a short description on what your product solves? What does it make better/faster/more efficient/more effective?',
        germanTooltip: 'Welches konkrete Problem, oder welche Ineffizienz lösen Sie mit ihrem Produkt?',
        validations: '150',
        labelClassName: 'profile-label',
        valueClassName: 'profile-value',
        type: 'textArea',
        typeValues: null
     },
     applicationIndustry: {
       name: 'applicationIndustry',
       englishLabel: 'Application Industry',
       germanLabel: 'Anwendung - Industrie',
       component: 'dropdownMultiple',
       englishTooltip: 'Companies from which industries are particularly interested in your product/service?',
       germanTooltip: 'Gibt es Industrien, für die Ihr Produkt besonders interessant ist?',
       validations: '',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'dropdownspecial',
       typeValues: values && values.cmsData && multiSelectValues(chunk(values.cmsData.industry.split('\n')))
     },
     applicationSector: {
       name: 'applicationSector',
       englishLabel: 'Application Sector',
       germanLabel: 'Anwendung - Sub-Sektoren',
       component: 'dropdownspecial',
       englishTooltip: 'Companies from which sectors are particulalry interested in your product/services?',
       germanTooltip: 'Gibt es Sektoren, für die Ihr Produkt besonders interessant ist?',
       validations: '',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'dropdownMultiple',
       typeValues: values && values.cmsData && multiSelectValues(chunk(values.cmsData.sector.split('\n'))),
       conditionalValues: {
         Energy: ['Energy Equipment & Services', 'Oil, Gas & Consumable Fuels'],
         Materials: ['Chemicals', 'Construction Materials', 'Containers & Packaging', 'Metals & Mining', 'Paper and Forest Products'],
         Industrials: ['Aerospace & Defense', 'Building Products', 'Construction & Engineering', 'Electrical Equipment', 'Industrial Conglomerates', 'Machinery', 'Commercial Services & Supplies', 'Professional Services', 'Transportation'],
         'Automobiles & Components': ['Auto Components', 'Automobiles'],
         'Consumer Durables & Apparel': ['Household Durables', 'Leisure Products', 'Textiles, Apparel & Luxury Goods'],
         'Consumer Services': ['Hotels, Restaurants & Leisure', 'Diversified Consumer Services', 'Media', 'Retailing'],
         'Consumer Staples': ['Food & Staples Retailing', 'Beverages', 'Food Products', 'Tobacco', 'Household & Personal Products'],
         'Health Care': ['Health Care Equipment & Supplies', 'Health Care Technology', 'Biotechnology', 'Pharmaceuticals', 'Life Sciences'],
         Financials: ['Banks', 'Thrifts & Mortgage Finance', 'Diversified Financial Services', 'Consumer Finance', 'Capital Markets', 'Insurance'],
         'Information Technology': ['Internet Software & Services', 'IT Services', 'Software', 'Technology Hardware & Equipment', 'Electronic Equipment, Instruments & Components', 'Office Electronics', 'Semiconductor Equipment & Products', 'Internet of Things'],
         'Telecommunication Services': ['Diversified Telecommunication Services'],
         Utilities: ['Electric Utilities', 'Gas Utilities', 'Multi-Utilities', 'Water Utilities', 'Independent Power and Renewable Electricity Producers'],
         'Real Estate': ['Equity Real Estate Investment Trusts (REITs)', 'Real Estate Management & Development']
       }
     },
     applicationSubSector: {
       name: 'applicationSubSector',
       englishLabel: 'Application Sub-Sector',
       germanLabel: 'Anwendung - Sub-Sektoren',
       component: 'dropdownspecial',
       englishTooltip: 'Companies from which Sub-Sectors are particularly interested in your product/services?',
       germanTooltip: 'Gibt es Sub-Sektoren, für die Ihr Produkt besonders interessant ist?',
       validations: '',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'dropdownMultiple',
       typeValues: values && values.cmsData && multiSelectValues(chunk(values.cmsData.sub_sector.split('\n'))),
       conditionalValues: {
         'Energy Equipment & Services': ['Oil & Gas Drilling', 'Oil & Gas Equipment & Services'],
         'Oil, Gas & Consumable Fuels': ['Integrated Oil & Gas', 'Oil & Gas Exploration & Production', 'Oil & Gas Refining & Marketing', 'Oil & Gas Storage & Transportation', 'Coal & Consumable Fuels'],
         Chemicals: ['Commodity Chemicals', 'Diversified Chemicals', 'Fertilizers & Agricultural Chemicals', 'Industrial Gases', 'Specialty Chemicals'],
         'Construction Materials': [],
         'Containers & Packaging': ['Metal & Glass Containers', 'Paper Packaging'],
         'Metals & Mining': ['Aluminum', 'Diversified Metals & Mining', 'Gold', 'Precious Metals & Minerals', 'Silver', 'Steel'],
         'Paper and Forest Products': ['Forest Products', 'Paper Products'],
         'Aerospace & Defense': [],
         'Building Products': [],
         'Construction & Engineering': [],
         'Electrical Equipment': ['Electrical Components & Equipment', 'Heavy Electrical Equipment'],
         'Industrial Conglomerates': [],
         Machinery: ['Construction Machinery & Heavy Trucks', 'Agricultural & Farm Machinery', 'Industrial Machinery'],
         'Commercial Services & Supplies': ['Commercial Printing', 'Data Processing Services', 'Diversified Commercial & Professional Services', 'Environmental & Facilities Services', 'Office Services & Supplies', 'Diversified Support Services', 'Security & Alarm Services'],
         'Professional Services': ['Human Resource & Employment Services', 'Research & Consulting Services'],
         Transportation: ['Air Freight & Logistics', 'Airlines', 'Marine', 'Road & Rail', 'Transportation Infrastructure'],
         'Auto Components': ['Auto Parts & Equipment', 'Tires & Rubber'],
         Automobiles: ['Automobile Manufacturers', 'Motorcycle Manufacturers'],
         'Household Durables': ['Consumer Electronics', 'Home Furnishings', 'Homebuilding', 'Household Appliances', 'Housewares & Specialties'],
         'Leisure Products': [],
         'Textiles, Apparel & Luxury Goods': ['Apparel, Accessories & Luxury Goods', 'Footwear', 'Textiles'],
         'Hotels, Restaurants & Leisure': ['Casinos & Gaming', 'Hotels, Resorts & Cruise Lines', 'Leisure Facilities', 'Restaurants'],
         'Diversified Consumer Services': ['Education Services', 'Specialized Consumer Services'],
         Media: ['Advertising', 'Broadcasting', 'Cable & Satellite', 'Movies & Entertainment', 'Publishing'],
         Retailing: ['Catalog Retail', 'Internet Retail', 'Department Stores', 'General Merchandise Stores', 'Apparel Retail', 'Computer & Electronics Retail', 'Home Improvement Retail', 'Specialty Stores', 'Automotive Retail', 'Homefurnishing Retail'],
         'Food & Staples Retailing': ['Drug Retail', 'Food Distributors', 'Food Retail', 'Hypermarkets & Super Centers'],
         Beverages: ['Brewers', 'Distillers & Vintners', 'Soft Drinks'],
         'Food Products': ['Agricultural Products', 'Meat, Poultry & Fish', 'Packaged Foods & Meats'],
         Tobacco: [],
         'Household & Personal Products': ['Household Products', 'Personal Products'],
         'Health Care Equipment & Supplies': ['Health Care Equipment', 'Health Care Supplies', 'Health Care Distributors', 'Health Care Services', 'Health Care Facilities', 'Managed Health Care'],
         'Health Care Technology': [],
         Biotechnology: [],
         Pharmaceuticals: [],
         'Life Sciences': [],
         Banks: ['Diversified Banks', 'Regional Banks'],
         'Thrifts & Mortgage Finance': ['Thrifts & Mortgage Finance'],
         'Diversified Financial Services': ['Consumer Finance', 'Other Diversified Financial Services', 'Multi-Sector Holdings', 'Specialized Finance'],
         'Consumer Finance': [],
         'Capital Markets': ['Asset Management & Custody Banks', 'Investment Banking & Brokerage', 'Diversified Capital Markets'],
         Insurance: ['Insurance Brokers', 'Life & Health Insurance', 'Multi-line Insurance', 'Property & Casualty Insurance', 'Reinsurance'],
         'Internet Software & Services': [],
         'IT Services': ['IT Consulting & Other Services', 'Data Processing & Outsourced Services'],
         Software: ['Application Software', 'Systems Software', 'Home Entertainment Software'],
         'Technology Hardware & Equipment': ['Communications Equipment', 'Networking Equipment', 'Telecommunications Equipment', 'Computer Hardware', 'Computer Storage & Peripherals', 'Technology Hardware, Storage & Peripherals'],
         'Electronic Equipment, Instruments & Components': ['Electronic Equipment & Instruments', 'Electronic Components', 'Electronic Manufacturing Services', 'Technology Distributors'],
         'Office Electronics': ['Office Electronics'],
         'Semiconductor Equipment & Products': ['Semiconductor Equipment', 'Semiconductors'],
         'Internet of Things': ['Internet of Things'],
         'Diversified Telecommunication Services': ['Alternative Carriers', 'Integrated Telecommunication Services'],
         'Wireless Telecommunication Services': [],
         'Electric Utilities': [],
         'Gas Utilities': [],
         'Multi-Utilities': [],
         'Water Utilities': [],
         'Independent Power and Renewable Electricity Producers': ['Independent Power Producers & Energy Traders', 'Renewable Electricity'],
         'Equity Real Estate Investment Trusts (REITs)': ['Industrial REITs', 'Hotel & Resort REITs', 'Office REITs', 'Health Care REITs', 'Residential REITs', 'Retail REITs', 'Specialized REITs'],
         'Real Estate Management & Development': ['Diversified Real Estate Activities', 'Real Estate Operating Companies', 'Real Estate Development', 'Real Estate Services']
       }
     },
     applicationValueChain: {
       name: 'applicationValueChain',
       englishLabel: 'Application for Value Chain',
       germanLabel: 'Wertschöpfungskette',
       component: 'dropdownMultiple',
       englishTooltip: 'Define the sector your product solves probelms',
       germanTooltip: 'An welchem Schritt in der Wertschöpfungskette bzw. für welche Geschäftsfunktion kann ihr Produkt/Service eingesetzt werden?',
       validations: '',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'dropdownMultiple',
       typeValues: values && values.cmsData && multiSelectValues(chunk(values.cmsData.value_chain_position.split('\n')))
     },
     applicationBusinessType: {
       name: 'applicationBusinessType',
       englishLabel: 'Application for Business Type',
       germanLabel: 'Anwendung für Geschäftsart',
       component: 'dropdownMultiple',
       englishTooltip: 'For which Business Types are your products and services most interesting?',
       germanTooltip: 'Für welche Geschäftsarten sind ihre Produkte und Dienstleistungen besonders interessant?',
       validations: '',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'dropdownMultiple',
       typeValues: values && values.cmsData && multiSelectValues(chunk(values.cmsData.business_type.split('\n')))
     },
     applicationKeyActivities: {
       name: 'applicationKeyActivities',
       englishLabel: 'Supports Key Activities',
       germanLabel: 'Für Hauptaktivitäten',
       component: 'multiSelect',
       englishTooltip: 'Which Key Operating Activities get supported by your product?',
       germanTooltip: 'Welche Hauptaktivitäten wer den durch ihre Produkte und Dienstleistungen unterstützt oder übernommen?',
       validations: '',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'multiSelect',
       typeValues: null
     },
     applicationKeyResources: {
       name: 'applicationKeyResources',
       englishLabel: 'Improves Key Resources',
       germanLabel: 'Für wichtigste Ressourcen',
       component: 'multiSelect',
       englishTooltip: 'Which Key Resources do your products and services constitute or support?',
       germanTooltip: 'Welche wichtigen Ressourcen stellt das Produkt dar, bzw. welche Ressourcen werden unterstützt?',
       validations: '',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'multiSelect',
       typeValues: null
     },
     applicationCostStructure: {
       name: 'applicationCostStructure',
       englishLabel: 'Reduces Cost Structures',
       germanLabel: 'Für Kostenstruktur',
       component: 'multiSelect',
       englishTooltip: 'Which costs are reduced through your product/service?',
       germanTooltip: 'Welche Kostenpunkte kann das Produkt bzw. die Dienstleistung senken?',
       validations: '',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'multiSelect',
       typeValues: null
     },
     digitalizationScope: {
       name: 'digitalizationScope',
       englishLabel: 'Digitilization Scope',
       germanLabel: 'Digitalisierungsstadium',
       component: 'dropdownMultiple',
       engglishTooltip: 'Please choose the level of digitalization that the product establishes.',
       germanTooltip: 'Wählen Sie die Kategorie, die das Digitalisierungsstadium ihrer Lösung am besten beschreibt.',
       validations: '',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'dropdownMultiple',
       typeValues: values && values.cmsData && multiSelectValues(chunk(values.cmsData.digitalization_scope.split('\n')))
     }
   }, /* Aplication Domain END */
   valuePrice: {
     applicationValueProposition: {
       name: 'applicationValueProposition',
       englishLabel: 'Value Proposition',
       germanLabel: 'Werteproposition',
       component: 'textArea',
       englishTooltip: 'What are the key benefits that your product/service delivers to your customers/users?',
       germanTooltip: 'Beschreiben Sie die Werteproposition, also die wichtigsten Vorteile, die Ihre Kunden durch ihr Produkt erhalten',
       validations: '150',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'textArea',
       typeValues: null
     },
     uniqueSellingPoints: {
       name: 'uniqueSellingPoints',
       englishLabel: 'Unique SellingPoints',
       germanLabel: 'Alleinstellungsmerkmale',
       component: 'textArea',
       englishTooltip: 'What makes your product/service unique as compared to other solutions?',
       germantooltip: 'Welche Alleinstellungsmerkmale machen Ihr Produkt einzigartig im Vergleich zu alternative Produkten/Dienstleistungen?',
       validations: '150',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'textArea',
       typeValues: null
     },
     productTechnologies: {
       name: 'productTechnologies',
       englishLabel: 'Product Technologies',
       germanLabel: 'Technologien',
       placeholder: 'Product Technologies',
       component: 'multiSelect',
       englishTooltip: 'Which technologies do you use in your product?',
       germanTooltip: 'Technologien',
       validations: '',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'multiSelect',
       typeValues: null
     },
     compatibileTechnologies: {
       name: 'compatibileTechnologies',
       englishLabel: 'Compatible Technologies',
       germanLabel: 'Kompatible Technologien',
       component: 'multiSelect',
       englishTooltip: 'Describe relevant compatible technologies that can be used in combination with this product',
       germanTooltip: 'Welche Technologien sind zusammen mit ihrem Produkt anwendbar und kompatibel?',
       validations: '',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'multiSelect',
       typeValues: null
     },
     requirements: {
       name: 'requirements',
       englishLabel: 'Requirements for use',
       germanLabel: 'Nutzungsvoraussetzungen',
       component: 'multiSelect',
       englishTooltip: 'Describe any important requirements and prerequisites that are necessary to use the product',
       germanTooltip: 'Gibt es technische oder Nutzer-spezifische Voraussetzungen, um Ihr Produkt zu verwenden?',
       validations: '',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'multiSelect',
       typeValues: null
     },
     patents: {
        name: 'patents',
        englishLabel: 'Patents',
        germanLabel: 'Patente',
        component: 'multiSelect',
        englishTooltip: 'Does your product/service rely on patents?',
        germanTooltip: 'Ist ihr Produkt patentiert? Falls ja, beschreiben Sie diese kurz',
        validations: '50',
        labelClassName: 'profile-label',
        valueClassName: 'profile-value',
        type: 'multiSelect',
        typeValues: null
     },
     pricingIndicationMin: {
       name: 'pricingIndicationMin',
       englishLabel: 'Total Price Range (min)',
       germanLabel: 'Gesamtkosten (min)',
       placeholder: 'Min',
       component: 'number',
       englishTooltip: 'Indicate the total price range in Euros that your customers should expect to use your product. We are aware that the exact price may depend on many individual factors.',
       germanTooltip: 'Indizieren Sie die Gesamtkosten ihres Produkts/Service. Wir sind uns bewusst, dass der genaue Preis ggf. von individuellen Faktoren abhängt',
       validations: '50',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'string',
       typeValues: null
     },
     pricingIndicationMax: {
       name: 'pricingIndicationMax',
       englishLabel: 'Total Price Range (max)',
       germanLabel: 'Gesamtkosten (max)',
       placeholder: 'Max',
       component: 'number',
       englishTooltip: 'Indicate the total price range in Euros that your customers should expect to use your product. We are aware that the exact price may depend on many individual factors.',
       germanTooltip: 'Indizieren Sie die Gesamtkosten ihres Produkts/Service. Wir sind uns bewusst, dass der genaue Preis ggf. von individuellen Faktoren abhängt',
       validations: '50',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'string',
       typeValues: null
     }
   }, /* Value Price END */
   operationDetails: {
     capacityIndication: {
       name: 'capacityIndication',
       englishLabel: 'Capacity/Scalability',
       germanLabel: 'Kapazität & Skalierbarkeit',
       component: 'multiSelect',
       englishTooltip: 'Indicate the capacity of your product/service, e.g. in terms of users you can accommodate, volumes provided per month/year, number of units, etc.',
       germanTooltip: 'Indizieren Sie die Kapazität bzw. Skalierbarkeit ihres Produkts, z.B. bezüglich der Nutzeranzahl, Stückzahl oder Volumen, das Sie beliefern können.',
       validations: '',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'multiSelect',
       typeValues: null
     },
     delivery: {
       name: 'delivery',
       englishLabel: 'Delivery/construction time',
       germanLabel: 'Liefer-/Projektzeitraum',
       component: 'multiSelect',
       englishTooltip: 'Indicate the time required to produce and deliver your product/service. You may indicate a range',
       germanTooltip: 'Liefer-/Projektzeitraum',
       validations: '',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'multiSelect',
       typeValues: null
     },
     integration: {
       name: 'integration',
       englishLabel: 'Integration/Adaptation',
       germanLabel: 'Integrationsprozess',
       component: 'multiSelect',
       englishTooltip: 'How difficult or easy is it for customers/users to integrate and adapt your product?',
       germanTooltip: 'Gibt es Hürden oder wichtige Faktoren, die bei der Nutzung und Integration ihres Angebots berücksichtigt werden sollten?',
       validations: '',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'multiSelect',
       typeValues: null
     },
     maintenance: {
       name: 'maintenance',
       englishLabel: 'Maintenance/Service',
       germanLabel: 'Wartung',
       component: 'multiSelect',
       englishTooltip: 'Are there important maintenance or service costs related to the product? Are updates required?',
       germanTooltip: 'Gibt es wichtige Faktoren, die bezüglich Instandhaltung berücksichtigt werden müssen oder Kosten verursachen?',
       validations: '',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'multiSelect',
       typeValues: null
     },
     geographicalMarkets: {
       name: 'geographicalMarkets',
       englishLabel: 'Geographical Markets served',
       germanLabel: 'Geographische Märkte',
       component: 'multiSelectAutoSuggest',
       englishTooltip: 'Indicate the geographical regions that that you are able to serve',
       germanTooltip: 'Welche geographischen Märkte bedient ihr Unternehmen?',
       validations: '',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'multiSelectAutoSuggest',
       typeValues: values && values.cmsData && multiSelectValues(chunk(values.cmsData.country.split('\n')))
     },
     industryStandards: {
       name: 'industryStandards',
       englishLabel: 'Product/Industry Standards',
       germanLabel: 'Standards & Zertifizierungen',
       placeholder: 'Product/Industry Standards',
       component: 'multiSelect',
       englishTooltip: 'Does your product/service follow any Industrial Standards such as ISO or DIN classifications?',
       germanTooltip: 'Folgt ihr Produkt Industriestandards oder hat es Zertifizierungen erhalten?',
       validations: '',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'multiSelect',
       typeValues: null
     },
     dataSecurity: {
       name: 'dataSecurity',
       englishLabel: 'Data Security',
       germanLabel: 'Datensicherheit',
       placeholder: 'Data Security',
       component: 'textArea',
       englishTooltip: 'Are there important data security considerations when using your product/service?',
       germanTooltip: 'Gibt es wichtige Datenschutz-Themen bei der Nutzung ihres Produkts zu berücksichtigen?',
       validations: '300',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'textArea',
       typeValues: null
     },
     segmentsDescription: {
       name: 'segmentsDescription',
       englishLabel: 'Target segment description',
       germanLabel: 'Zielsegments',
       component: 'textArea',
       englishTooltip: 'Describe how you see your typical target segment of users and customers',
       germanTooltip: 'Beschreiben Sie das Zielsegment bzw. den idealtypischen Kunden, den Sie versuchen zu erreichen',
       validations: '300',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'textArea',
       typeValues: null
     },
     regulatoryCondition: {
       name: 'regulatoryCondition',
       englishLabel: 'Legal/regulatory considerations',
       germanLabel: 'Rechtliche Nutzungshinweise',
       placeholder: 'Legal/regulatory considerations',
       component: 'textArea',
       englishTooltip: 'Descibe potential legal or regulatory considerations to be taken into account when using your product',
       germanTooltip: 'Beschreiben Sie potenzielle Hinweise zu rechtlichen Themen, die die Nutzung ihres Angebots betreffen könnten',
       validations: '300',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'textArea',
       typeValues: null
     },
     productRisk: {
       name: 'productRisk',
       englishLabel: 'Product Risks',
       germanLabel: 'Nutzungsrisiken',
       component: 'textArea',
       englishTooltip: 'Describe any risks that may arise from using your product/service that your customers and users should be aware of',
       germanTooltip: 'Beschreiben Sie, falls vorhanden, Risiken, die durch Nutzung des Produkts entstehen',
       validations: '300',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'textArea',
       typeValues: null
     },
     otherProductAttributes: {
       name: 'otherProductAttributes',
       englishLabel: 'Other Product Attributes',
       germanLabel: 'Andere Eigenschaften',
       placeholder: 'Other Product Attributes',
       component: 'multiSelect',
       englishTooltip: 'Describe any other relevant product attributes that were not mentioned',
       germanTooltip: 'Gibt es andere Produkteigenschaften, die bisher nicht aufgeführt wurden?',
       validations: '',
       labelClassName: 'profile-label',
       valueClassName: 'profile-value',
       type: 'multiSelect',
       typeValues: null
     }
   }/* Operation Details END */
};
}
