export const INVITE_TEAM_REQUEST = 'INVITE_TEAM_REQUEST';
export const TEAM_VALIDATE_EMAIL_REQUEST = 'TEAM_VALIDATE_EMAIL_REQUEST';
export const INVITE_PARTNER_REQUEST = 'INVITE_PARTNER_REQUEST';
export const PARTNER_VALIDATE_EMAIL_REQUEST = 'PARTNER_VALIDATE_EMAIL_REQUEST';

export const INVITE_TEAM_SUCCESS = 'INVITE_TEAM_SUCCESS';
export const TEAM_VALIDATE_EMAIL_SUCCESS = 'TEAM_VALIDATE_EMAIL_SUCCESS';
export const INVITE_PARTNER_SUCCESS = 'PARTNER_TEAM_SUCCESS';
export const PARTNER_VALIDATE_EMAIL_SUCCESS = 'PARTNER_VALIDATE_EMAIL_SUCCESS';
