 export const FETCH_MATCHES_REQUEST = 'FETCH_MATCHES_REQUEST';
export const FETCH_MATCHES_SUCCESS = 'FETCH_MATCHES_SUCCESS';
export const REFRESH_MATCH_REQUEST = 'REFRESH_MATCH_REQUEST';

export const SAVE_MATCH_REQUEST = 'SAVE_MATCH_REQUEST';
export const SAVE_MATCH_SUCCESS = 'SAVE_MATCH_SUCCESS';

export const REMOVE_SAVED_MATCH_REQUEST = 'REMOVE_SAVED_MATCH_REQUEST';
export const REMOVE_SAVED_MATCH_SUCCESS = 'REMOVE_SAVED_MATCH_SUCCESS';
export const CREATE_MATCH_REQUEST = 'CREATE_MATCH_REQUEST';

export const TOGGLE_MATCHES_LOADED = 'TOGGLE_MATCHES_LOADED';
export const SAVE_UPDATE_MATCHES_REQUEST = 'SAVE_UPDATE_MATCHES_REQUEST';
export const SAVE_UPDATE_MATCHES_SUCCESS = 'SAVE_UPDATE_MATCHES_SUCCESS';
export const CREATE_MATCH_SUCCESS = 'CREATE_MATCH_SUCCESS';


export const UPDATE_MATCHES_REQUEST = 'UPDATE_MATCHES_REQUEST';
export const UPDATE_MATCHES_SUCCESS = 'UPDATE_MATCHES_SUCCESS';
export const REFRESH_MATCH_SUCCESS = 'REFRESH_MATCH_SUCCESS';

export const CONTACT_MATCH_EMAIL_REQUEST = 'CONTACT_MATCH_EMAIL_REQUEST';
export const CONTACT_MATCH_EMAIL_SUCCESS = 'CONTACT_MATCH_EMAIL_SUCCESS';
