export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_TARGET_PROFILE_REQUEST = 'GET_TARGET_PROFILE_REQUEST';
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_TARGET_PROFILE_REQUEST = 'UPDATE_TARGET_PROFILE_REQUEST';
export const MANUAL_ADMIN_PROFILE_REQUEST = 'MANUAL_ADMIN_PROFILE_REQUEST';
export const REALTIME_ADMIN_PROFILE_REQUEST = 'REALTIME_ADMIN_PROFILE_REQUEST';
export const GET_COMPNAME_DB_REQUEST = 'GET_COMPNAME_DB_REQUEST';


export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_TARGET_PROFILE_SUCCESS = 'GET_TARGET_PROFILE_SUCCESS';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_TARGET_PROFILE_SUCCESS = 'UPDATE_TARGET_PROFILE_SUCCESS';
export const MANUAL_ADMIN_PROFILE_SUCCESS = 'MANUAL_ADMIN_PROFILE_SUCCESS';
export const GET_COMPNAME_DB_SUCCESS = 'GET_COMPNAME_DB_SUCCESS';


export const FETCH_ADMIN_PROFILE_REQUEST = 'FETCH_ADMIN_PROFILE_REQUEST';
export const FETCH_ADMIN_PROFILE_SUCCESS = 'FETCH_ADMIN_PROFILE_SUCCESS';
export const GET_FEED_PROFILE_REQUEST = 'GET_FEED_PROFILE_REQUEST';

export const UPDATE_ADMIN_PROFILE_REQUEST = 'UPDATE_ADMIN_PROFILE_REQUEST';
export const UPDATE_ADMIN_PROFILE_SUCCESS = 'UPDATE_ADMIN_PROFILE_SUCCESS';

export const GET_PROFILE_SIGNUP_REQUEST = 'GET_PROFILE_SIGNUP_REQUEST';
export const GET_PROFILE_SIGNUP_SUCCESS = 'GET_PROFILE_SIGNUP_SUCCESS';
export const GET_FEED_PROFILE_SUCCESS = 'GET_FEED_PROFILE_SUCCESS';

export const GET_PROFILE_NAME_REQUEST = 'GET_PROFILE_NAME_REQUEST';
export const GET_PROFILE_NAME_SUCCESS = 'GET_PROFILE_NAME_SUCCESS';
export const REALTIME_ADMIN_PROFILE_SUCCESS = 'REALTIME_ADMIN_PROFILE_SUCCESS';

// Logo actions are local state only
// -> synced to DB by UPDATE_PROFILE actions when user clicks 'Save'
export const UPDATE_LOGO_REQUEST = 'UPDATE_LOGO_REQUEST';
export const UPDATE_LOGO_SUCCESS = 'UPDATE_LOGO_SUCCESS';
export const UPDATE_LOGO_FAIL = 'UPDATE_LOGO_FAIL';
export const DELETE_LOGO_REQUEST = 'DELETE_LOGO_REQUEST';
export const DELETE_LOGO_SUCCESS = 'DELETE_LOGO_SUCCESS';

export const TOGGLE_PROFILE_EDIT = 'TOGGLE_PROFILE_EDIT';
export const TOGGLE_NETWORK_PROFILE = 'TOGGLE_NETWORK_PROFILE';
export const TOGGLE_LOADED = 'TOGGLE_LOADED';
