export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const GET_PROJECT_REQUEST = 'GET_PROJECT_REQUEST';
export const UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST';
export const UPDATE_STATUS_PROJECT_REQUEST = 'UPDATE_STATUS_PROJECT_REQUEST';
export const GET_TARGET_PROFILE_REQUEST = 'GET_TARGET_PROFILE_REQUEST';
export const UPDATE_CURRENT_PROJECT_REQUEST = 'UPDATE_CURRENT_PROJECT_REQUEST';
export const CONTACT_PROJECT_REQUEST = 'CONTACT_PROJECT_REQUEST';
export const GET_VIEW_PROJECT_REQUEST = 'GET_VIEW_PROJECT_REQUEST';

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_STATUS_PROJECT_SUCCESS = 'UPDATE_STATUS_PROJECT_SUCCESS';
export const GET_TARGET_PROFILE_SUCCESS = 'GET_TARGET_PROFILE_SUCCESS';
export const UPDATE_CURRENT_PROJECT_SUCCESS = 'UPDATE_CURRENT_PROJECT_SUCCESS';
export const CONTACT_PROJECT_SUCCESS = 'CONTACT_PROJECT_SUCCESS';
export const GET_VIEW_PROJECT_SUCCESS = 'GET_VIEW_PROJECT_SUCCESS';

export const FETCH_ADMIN_PROFILE_REQUEST = 'FETCH_ADMIN_PROFILE_REQUEST';
export const FETCH_ADMIN_PROFILE_SUCCESS = 'FETCH_ADMIN_PROFILE_SUCCESS';


export const GET_PROJECT_SIGNUP_REQUEST = 'GET_PROJECT_SIGNUP_REQUEST';
export const GET_PROJECT_SIGNUP_SUCCESS = 'GET_PROJECT_SIGNUP_SUCCESS';

export const UPDATE_ADMIN_PROFILE_REQUEST = 'UPDATE_ADMIN_PROFILE_REQUEST';
export const UPDATE_ADMIN_PROFILE_SUCCESS = 'UPDATE_ADMIN_PROFILE_SUCCESS';


// Logo actions are local state only
// -> synced to DB by UPDATE_PROFILE actions when user clicks 'Save'

export const UPDATE_FILE_REQUEST = 'UPDATE_FILE_REQUEST';
export const UPDATE_FILE_SUCCESS = 'UPDATE_FILE_SUCCESS';
export const UPDATE_FILE_FAIL = 'UPDATE_FILE_FAIL';
export const DELETE_FILE_REQUEST = 'DELETE_FILE_REQUEST';
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';
export const DELETE_FILE_APPLICATION_REQUEST = 'DELETE_FILE_APPLICATION_REQUEST';
export const DELETE_FILE_APPLICATION_SUCCESS = 'DELETE_FILE_APPLICATION_SUCCESS';
export const UPDATE_FILE_APPLICATION_REQUEST = 'UPDATE_FILE_APPLICATION_REQUEST';
export const UPDATE_FILE_APPLICATION_SUCCESS = 'UPDATE_FILE_APPLICATION_SUCCESS';
export const UPDATE_FILE_APPLICATION_FAIL = 'UPDATE_FILE_APPLICATION_FAIL';


export const TOGGLE_PROJECTS_EDIT = 'TOGGLE_PROJECTS_EDIT';
