// ###############
// I/O TYPES
// ###############
export const SAVE_SEARCH_REQUEST = 'SAVE_SEARCH_REQUEST';
export const SAVE_SEARCH_SUCCESS = 'SAVE_SEARCH_SUCCESS';

export const GET_SEARCH_REQUEST = 'GET_SEARCH_REQUEST';
export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS';

export const GET_SEARCH_SIGNUP_REQUEST = 'GET_SEARCH_SIGNUP_REQUEST';
export const GET_SEARCH_SIGNUP_SUCCESS = 'GET_SEARCH_SIGNUP_SUCCESS';

export const UPDATE_SEARCH_REQUEST = 'UPDATE_SEARCH_REQUEST';
export const UPDATE_SEARCH_SUCCESS = 'UPDATE_SEARCH_SUCCESS';

export const DELETE_SEARCH_REQUEST = 'DELETE_SEARCH_REQUEST';
export const DELETE_SEARCH_SUCCESS = 'DELETE_SEARCH_SUCCESS';

export const UPDATE_SEARCH_PREFERENCES_REQUEST = 'UPDATE_SEARCH_PREFERENCES_REQUEST';
export const UPDATE_SEARCH_PREFERENCES_SUCCESS = 'UPDATE_SEARCH_PREFERENCES_SUCCESS';


// ###############
// UI TYPES
// ###############
export const TOGGLE_SEARCH_EDIT = 'TOGGLE_SEARCH_EDIT';
export const TOGGLE_LOADED = 'TOGGLE_LOADED';
