export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNOUT_REQUEST = 'SIGNOUT_REQUEST';
export const DELETE_ACCOUNT_REQUEST = 'DELETE_ACCOUNT_REQUEST';
export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const VALIDATE_EMAIL_REQUEST = 'VALIDATE_EMAIL_REQUEST';
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';


export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const VALIDATE_EMAIL_SUCCESS = 'VALIDATE_EMAIL_SUCCESS';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const GET_SETTING_REQUEST = 'GET_SETTING_REQUEST';
export const GET_SETTING_SUCCESS = 'GET_SETTING_SUCCESS';
export const UPDATE_SETTINGS_REQUEST = 'UPDATE_SETTINGS_REQUEST';
export const UPDATE_SETTINGS_SUCCESS = 'UPDATE_SETTINGS_SUCCESS';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const TOGGLE_FORGET_MODE = 'TOGGLE_FORGET_MODE';
export const GERMAN_MODE = 'GERMAN_MODE';
export const ENGLISH_MODE = 'ENGLISH_MODDE';
export const TOGGLE_SETTING_EDIT = 'TOGGLE_SETTING_EDIT';

export const NOTIFY_REQUEST = 'NOTIFY_REQUEST';
export const NOTIFY_SUCCESS = 'NOTIFY_SUCCESS';
