import {multiSelectValues, chunk} from '../../util/multiSelectValues';

export function ProductDetailSearch(values) {
return {
  productDetailSearch: {
    meta: {
      name: 'productDetailSearch',
      type: 'Products/Services - I want to specify the details of what I am looking for',
      createdAt: null
    },
    fields: {
      productDetailSearchName: {
        name: 'productDetailSearchName',
        englishLabel: 'Search Name',
        germanLabel: 'Search Name',
        component: 'text',
        englishTooltip: 'Indicate the name of your search. If you do not have a name, a short descriptive title can substitute',
        germanTooltip: 'Fügen Sie den Namen oder einen kurzen, beschreibenden Titel für Ihr Search hinzu',
        validations: '25',
        labelClassName: 'profile-label',
        valueClassName: 'profile-value',
        type: 'string',
        typeValues: null,
        ko:'no'
    },
    businessObjective: {
        name: 'businessObjective',
        englishLabel: 'Business objective',
        germanLabel: 'Geschäftsziel',
        component: 'dropdownMultiple',
        englishTooltip: 'What is the business objective that you aim to accomplish with the product/service you seek?',
        germanTooltip: 'Welches Geschäftsziel wollen Sie durch die Lösung erreichen?',
        validations: '300',
        labelClassName: 'profile-label',
        valueClassName: 'profile-value',
        type: 'dropdownMultiple',
        typeValues: values && values.cmsData && multiSelectValues(chunk(values.cmsData.business_objectives.split('\n'))),
        ko:'yes'
    },
    technologyField: {
        name: 'technologyField',
        englishLabel: 'Technology Field',
        germanLabel: 'Technologie-Feld',
        component: 'dropdownMultiple',
        englishTooltip: 'Choose the Technologie Field that the solution you search belongs to',
        germanTooltip: 'Zu welchem Technologie-Feld gehört die Lösung, nach der Sie suchen?',
        type: 'dropdownMultiple',
        labelClassName: 'profile-label',
        valueClassName: 'profile-value',
        typeValues: values && values.cmsData && multiSelectValues(chunk(values.cmsData.technology_application_field.split('\n'))),
        ko:'yes'
    },
     productCategory: {
        name: 'productCategory',
        englishLabel: 'Product Category',
        germanLabel: 'Produktkategorie',
        component: 'multiSelect',
        englishTooltip: 'Which narrower product category describes the products/services you are searching?',
        germanTooltip: 'Welchen Produkt Kategorien lässt sich ihre Suche zuordnen?',
        type: 'multiSelect',
        labelClassName: 'profile-label',
        valueClassName: 'profile-value',
        typeValues: [{}],
        ko:'yes'
      },
     applicationIndustry: {
        name: 'applicationIndustry',
        englishLabel: 'For industry',
        germanLabel: 'Für Industrie',
        component: 'dropdownMultiple',
        englishTooltip: 'For which industry is the solution you search intended for? (Note: by default, we will choose your industry)',
        germanTooltip: 'Für welche Industrie ist die Lösung die Sie suchen gedacht? (Anmerkung: Sollten Sie hier keine Auswahl treffen, wird die Industrie ihres Unternehmens verwendet)',
        type: 'dropdownMultiple',
        labelClassName: 'profile-label',
        valueClassName: 'profile-value',
        typeValues: values && values.cmsData && multiSelectValues(chunk(values.cmsData.industry.split('\n'))),
        ko:'yes'
      },
      applicationSector: {
         name: 'applicationSector',
         englishLabel: 'For sector',
         germanLabel: 'Für Sektor',
         component: 'dropdownspecial',
         englishTooltip: 'For which sector is the solution you search intended for? (Note: by default, we will choose your sector)',
         germanTooltip: 'Für welchen Sektor ist die Lösung die Sie suchen gedacht? (Anmerkung: Sollten Sie hier keine Auswahl treffen, wird der Sektor ihres Unternehmens verwendet)',
         type: 'dropdownMultiple',
         labelClassName: 'profile-label',
         valueClassName: 'profile-value',
         typeValues: values && values.cmsData && multiSelectValues(chunk(values.cmsData.sector.split('\n'))),
         ko:'yes',
        conditionalValues: {
          Energy: ['Energy Equipment & Services', 'Oil, Gas & Consumable Fuels'],
          Materials: ['Chemicals', 'Construction Materials', 'Containers & Packaging', 'Metals & Mining', 'Paper and Forest Products'],
          Industrials: ['Aerospace & Defense', 'Building Products', 'Construction & Engineering', 'Electrical Equipment', 'Industrial Conglomerates', 'Machinery', 'Commercial Services & Supplies', 'Professional Services', 'Transportation'],
          'Automobiles & Components': ['Auto Components', 'Automobiles'],
          'Consumer Durables & Apparel': ['Household Durables', 'Leisure Products', 'Textiles, Apparel & Luxury Goods'],
          'Consumer Services': ['Hotels, Restaurants & Leisure', 'Diversified Consumer Services', 'Media', 'Retailing'],
          'Consumer Staples': ['Food & Staples Retailing', 'Beverages', 'Food Products', 'Tobacco', 'Household & Personal Products'],
          'Health Care': ['Health Care Equipment & Supplies', 'Health Care Technology', 'Biotechnology', 'Pharmaceuticals', 'Life Sciences'],
          Financials: ['Banks', 'Thrifts & Mortgage Finance', 'Diversified Financial Services', 'Consumer Finance', 'Capital Markets', 'Insurance'],
          'Information Technology': ['Internet Software & Services', 'IT Services', 'Software', 'Technology Hardware & Equipment', 'Electronic Equipment, Instruments & Components', 'Office Electronics', 'Semiconductor Equipment & Products', 'Internet of Things'],
          'Telecommunication Services': ['Diversified Telecommunication Services'],
          Utilities: ['Electric Utilities', 'Gas Utilities', 'Multi-Utilities', 'Water Utilities', 'Independent Power and Renewable Electricity Producers'],
          'Real Estate': ['Equity Real Estate Investment Trusts (REITs)', 'Real Estate Management & Development']
        }
       },
     applicationSubSector: {
        name: 'applicationSubSector',
        englishLabel: 'For sub-sector',
        germanLabel: 'Für Sub-Sektor',
        component: 'dropdownspecial',
        englishTooltip: 'For which sub-sector is the solution you search intended for? (Note: by default, we will choose your sub-sector)',
        germanTooltip: 'Für welchen Sub-Sektor ist die Lösung die Sie suchen gedacht? (Anmerkung: Sollten Sie hier keine Auswahl treffen, wird der Sub-Sektor ihres Unternehmens verwendet)',
        type: 'dropdownMultiple',
        labelClassName: 'profile-label',
        valueClassName: 'profile-value',
        typeValues: values && values.cmsData && multiSelectValues(chunk(values.cmsData.sub_sector.split('\n'))),
        ko:'yes',
        conditionalValues: {
          'Energy Equipment & Services': ['Oil & Gas Drilling', 'Oil & Gas Equipment & Services'],
          'Oil, Gas & Consumable Fuels': ['Integrated Oil & Gas', 'Oil & Gas Exploration & Production', 'Oil & Gas Refining & Marketing', 'Oil & Gas Storage & Transportation', 'Coal & Consumable Fuels'],
          Chemicals: ['Commodity Chemicals', 'Diversified Chemicals', 'Fertilizers & Agricultural Chemicals', 'Industrial Gases', 'Specialty Chemicals'],
          'Construction Materials': [],
          'Containers & Packaging': ['Metal & Glass Containers', 'Paper Packaging'],
          'Metals & Mining': ['Aluminum', 'Diversified Metals & Mining', 'Gold', 'Precious Metals & Minerals', 'Silver', 'Steel'],
          'Paper and Forest Products': ['Forest Products', 'Paper Products'],
          'Aerospace & Defense': [],
          'Building Products': [],
          'Construction & Engineering': [],
          'Electrical Equipment': ['Electrical Components & Equipment', 'Heavy Electrical Equipment'],
          'Industrial Conglomerates': [],
          Machinery: ['Construction Machinery & Heavy Trucks', 'Agricultural & Farm Machinery', 'Industrial Machinery'],
          'Commercial Services & Supplies': ['Commercial Printing', 'Data Processing Services', 'Diversified Commercial & Professional Services', 'Environmental & Facilities Services', 'Office Services & Supplies', 'Diversified Support Services', 'Security & Alarm Services'],
          'Professional Services': ['Human Resource & Employment Services', 'Research & Consulting Services'],
          Transportation: ['Air Freight & Logistics', 'Airlines', 'Marine', 'Road & Rail', 'Transportation Infrastructure'],
          'Auto Components': ['Auto Parts & Equipment', 'Tires & Rubber'],
          Automobiles: ['Automobile Manufacturers', 'Motorcycle Manufacturers'],
          'Household Durables': ['Consumer Electronics', 'Home Furnishings', 'Homebuilding', 'Household Appliances', 'Housewares & Specialties'],
          'Leisure Products': [],
          'Textiles, Apparel & Luxury Goods': ['Apparel, Accessories & Luxury Goods', 'Footwear', 'Textiles'],
          'Hotels, Restaurants & Leisure': ['Casinos & Gaming', 'Hotels, Resorts & Cruise Lines', 'Leisure Facilities', 'Restaurants'],
          'Diversified Consumer Services': ['Education Services', 'Specialized Consumer Services'],
          Media: ['Advertising', 'Broadcasting', 'Cable & Satellite', 'Movies & Entertainment', 'Publishing'],
          Retailing: ['Catalog Retail', 'Internet Retail', 'Department Stores', 'General Merchandise Stores', 'Apparel Retail', 'Computer & Electronics Retail', 'Home Improvement Retail', 'Specialty Stores', 'Automotive Retail', 'Homefurnishing Retail'],
          'Food & Staples Retailing': ['Drug Retail', 'Food Distributors', 'Food Retail', 'Hypermarkets & Super Centers'],
          Beverages: ['Brewers', 'Distillers & Vintners', 'Soft Drinks'],
          'Food Products': ['Agricultural Products', 'Meat, Poultry & Fish', 'Packaged Foods & Meats'],
          Tobacco: [],
          'Household & Personal Products': ['Household Products', 'Personal Products'],
          'Health Care Equipment & Supplies': ['Health Care Equipment', 'Health Care Supplies', 'Health Care Distributors', 'Health Care Services', 'Health Care Facilities', 'Managed Health Care'],
          'Health Care Technology': [],
          Biotechnology: [],
          Pharmaceuticals: [],
          'Life Sciences': [],
          Banks: ['Diversified Banks', 'Regional Banks'],
          'Thrifts & Mortgage Finance': ['Thrifts & Mortgage Finance'],
          'Diversified Financial Services': ['Consumer Finance', 'Other Diversified Financial Services', 'Multi-Sector Holdings', 'Specialized Finance'],
          'Consumer Finance': [],
          'Capital Markets': ['Asset Management & Custody Banks', 'Investment Banking & Brokerage', 'Diversified Capital Markets'],
          Insurance: ['Insurance Brokers', 'Life & Health Insurance', 'Multi-line Insurance', 'Property & Casualty Insurance', 'Reinsurance'],
          'Internet Software & Services': [],
          'IT Services': ['IT Consulting & Other Services', 'Data Processing & Outsourced Services'],
          Software: ['Application Software', 'Systems Software', 'Home Entertainment Software'],
          'Technology Hardware & Equipment': ['Communications Equipment', 'Networking Equipment', 'Telecommunications Equipment', 'Computer Hardware', 'Computer Storage & Peripherals', 'Technology Hardware, Storage & Peripherals'],
          'Electronic Equipment, Instruments & Components': ['Electronic Equipment & Instruments', 'Electronic Components', 'Electronic Manufacturing Services', 'Technology Distributors'],
          'Office Electronics': ['Office Electronics'],
          'Semiconductor Equipment & Products': ['Semiconductor Equipment', 'Semiconductors'],
          'Internet of Things': ['Internet of Things'],
          'Diversified Telecommunication Services': ['Alternative Carriers', 'Integrated Telecommunication Services'],
          'Wireless Telecommunication Services': [],
          'Electric Utilities': [],
          'Gas Utilities': [],
          'Multi-Utilities': [],
          'Water Utilities': [],
          'Independent Power and Renewable Electricity Producers': ['Independent Power Producers & Energy Traders', 'Renewable Electricity'],
          'Equity Real Estate Investment Trusts (REITs)': ['Industrial REITs', 'Hotel & Resort REITs', 'Office REITs', 'Health Care REITs', 'Residential REITs', 'Retail REITs', 'Specialized REITs'],
          'Real Estate Management & Development': ['Diversified Real Estate Activities', 'Real Estate Operating Companies', 'Real Estate Development', 'Real Estate Services']
        }
      },
      applicationValueChain: {
         name: 'applicationValueChain',
         englishLabel: 'For Business Function',
         germanLabel: 'Für Wertschöpfungsschritt',
         component: 'dropdownMultiple',
         englishTooltip: 'Choose the value chain position/support function for which the product/service is applied',
         germanTooltip: 'Wählen Sie den Schritt in der Wertschöpfungskette, den die Lösung unterstützen oder durchführen soll',
         type: 'dropdownMultiple',
         labelClassName: 'profile-label',
         valueClassName: 'profile-value',
         typeValues: values && values.cmsData && multiSelectValues(chunk(values.cmsData.value_chain_position.split('\n'))),
         ko:'yes'
      },
      applicationBusinessType: {
         name: 'applicationBusinessType',
         englishLabel: 'For business type',
         germanLabel: 'Für Geschäftsart',
         component: 'dropdownMultiple',
         englishTooltip: 'Choose the business type that the product/service you search is intendend for (Note: by default, we will choose your business type)',
         germanTooltip: 'Wählen Sie die Geschäftsart, für die die Lösung, die Sie suchen, gedacht ist. (Anmerkung: Sollten Sie keine Auswahl treffen, wird die Geschäftsart von ihrem Unternehmensprofil übernommen',
         type: 'dropdownMultiple',
         labelClassName: 'profile-label',
         valueClassName: 'profile-value',
         typeValues: values && values.cmsData && multiSelectValues(chunk(values.cmsData.business_type.split('\n'))),
         ko:'yes'
      },
       patents: {
          name: 'patents',
          englishLabel: 'Patented',
          germanLabel: 'Patent',
          component: 'dropdown',
          englishTooltip: 'Choose yes if the product should have patents',
          germanTooltip: 'Sollte die gesuchte Lösung patentiert sein?',
          type: 'dropdown',
          labelClassName: 'profile-label',
          valueClassName: 'profile-value',
          typeValues: ['Yes', 'No'],
          ko:'yes'
        },
      compatibileTechnologies: {
         name: 'compatibileTechnologies',
         englishLabel: 'Technologies needed',
         germanLabel: 'Technologien',
         component: 'multiSelect',
         englishTooltip: 'Are there particular technologies that you are looking for In the product/service?',
         germanTooltip: 'Gibt es bestimmte Technologien, die die Lösung verwenden sollte?',
         type: 'multiSelect',
         labelClassName: 'profile-label',
         valueClassName: 'profile-value',
         typeValues: [{}],
         ko:'yes'
       },
       digitalizationScopeMin: {
          name: 'digitalizationScopeMin',
          englishLabel: 'Digitalization scope (min.)',
          germanLabel: 'Digitalisierungsstadium (min.)',
          component: 'dropdown',
          englishTooltip: 'Are there particular technologies that you are looking for In the product/service?',
          germanTooltip: 'Gibt es bestimmte Technologien, die die Lösung verwenden sollte?',
          type: 'dropdown',
          labelClassName: 'profile-label',
          valueClassName: 'profile-value',
          ko:'yes',
         typeValues: ['Not digital', 'Digital documentation', 'Digital communication', 'Digital media presence (website, social media,...)', 'Digital data systems (ERP, CRM, CMS, …)', 'Automated data gathering', 'Automated data analytics', 'Digital hardware connection (Sensor data)', 'Hardware device communication (Internet of Things)', 'Artificial Intelligence & information processes', 'Artificial Intelligence & physical processes (Robotics)']
        },
       digitalizationScopeMax: {
         name: 'digitalizationScopeMax',
         englishLabel: 'Digitalization scope (max.)',
         germanLabel: 'Digitalisierungsstadium (max.)',
         component: 'dropdown',
         englishTooltip: 'Are there particular technologies that you are looking for In the product/service?',
         germanTooltip: 'Gibt es bestimmte Technologien, die die Lösung verwenden sollte?',
         type: 'dropdown',
         labelClassName: 'profile-label',
         valueClassName: 'profile-value',
         ko:'yes',
         typeValues: ['Not digital', 'Digital documentation', 'Digital communication', 'Digital media presence (website, social media,...)', 'Digital data systems (ERP, CRM, CMS, …)', 'Automated data gathering', 'Automated data analytics', 'Digital hardware connection (Sensor data)', 'Hardware device communication (Internet of Things)', 'Artificial Intelligence & information processes', 'Artificial Intelligence & physical processes (Robotics)']
       },
       totalBudget: {
         name: 'totalBudget',
         englishLabel: 'Total Budget (in Euros)',
         germanLabel: 'Gesamtbudget',
         component: 'number',
         validations: '15',
         englishTooltip: 'Give an indication of the total budget range that you are want to spend. We are aware that the exact budget details may depend on the solution offered to you',
         germanTooltip: 'Geben Sie einen groben Preisrahmen für die Gesamtkosten der Lösung. Wir sind uns bewusst, dass der genaue Preis vom Angebot abhängt',
         type: 'string',
         labelClassName: 'profile-label',
         valueClassName: 'profile-value',
         typeValues: null,
         ko:'no'
       },
       industryStandards: {
          name: 'industryStandards',
          englishLabel: 'Standards & Certificates',
          germanLabel: 'Standards & Zertifizierungent',
          component: 'multiSelect',
          englishTooltip: 'Indicate potential standards that the product/service needs to comply with',
          germanTooltip: 'Gibt es Standards oder Zertifizierungen, die das Produkt haben sollte?',
          type: 'multiSelect',
          labelClassName: 'profile-label',
          valueClassName: 'profile-value',
          typeValues: [{}],
          ko:'no'
        },
      otherProductAttributes: {
         name: 'company123',
         englishLabel: 'Other product requirements',
         germanLabel: 'Andere Produkteigenschaften',
         component: 'multiSelect',
         englishTooltip: 'Specify any other product requirements that were not yet mentioned',
         germanTooltip: 'Falls es weitere Eigenschaften gibt, die noch nicht genannt wurden, führen Sie diese hier auf',
         type: 'multiSelect',
         labelClassName: 'profile-label',
         valueClassName: 'profile-value',
         typeValues: [{}],
         ko:'no',
         special: 'checkbox-style-for-big-box'
       }
     }
    }
  };
}
