import LocalizedStrings from 'react-localization';

const strings = new LocalizedStrings({
  default: {},
  en: {
    headerSearch: 'Search Tech',
    headerSupply: 'Supply Tech',
    headerHowitWorks: 'How it Works',
    headerPrice: 'Pricing',
    headerAboutUs: 'About',
    headerSignup: 'Sign Up',
    headerLogin: 'Log In',
    headingDescription: 'EMPOWERING TECHNOLOGY',
    secondHeadingDescription: 'We make digital technology accessible to any business, to build a more innovative, collaborative and sustainable economy together.',
    useCasesHeading: 'Use Cases',
    useCasesHeading1: 'What we do',
    useCasesCard1Header: 'IoT & Machine Learning',
    useCasesCard1Title: 'Predictive maintenance',
    useCasesCard1Body: 'We have connected technology providers to equip a consumer durables product with a smart maintenance solution. A custom developed sensor, machine learning data analytics and a comprehensive user interface communicate maintenance needs to the product owner.',
    useCasesCard2Header: 'Enterprise Software',
    useCasesCard2Title: 'Production planning software',
    useCasesCard2Body: 'In order to improve production capacity and efficiency for an automotive supplier, we compared and selected a software tool to analyse the operational factory setup and production planning.',
    useCasesCard3Header: 'Virtual Reality',
    useCasesCard3Title: 'Emotional Marketing & Sales',
    useCasesCard3Body: 'Together with a mechanical engineering client, our team proposed a digital marketing & sales strategy, making heavy use of product demos with a virtual reality solution.',
    techHeader: 'Technologies',
    techHeader1: 'Discover 9500+ Technology providers',
    searchDigitalHeading: 'Search Tech',
    searchDigitalSubHeading1: 'My organisation is',
    searchDigitalSubHeading2: 'searching',
    searchDigitalSubHeading3: 'for digital solutions',
    supplyDigitalHeading: 'Supply Tech',
    supplyDigitalSubHeading1: 'My organisation is',
    supplyDigitalSubHeading2: 'offering',
    supplyDigitalSubHeading3: 'digital solutions',
    searchFirstMainDescription: 'Strategize',
    searchFirstSubDescription: 'Ideate, define your goals and get ready for digital change',
    searchSecondMainDescription: 'Decide',
    searchSecondSubDescription: 'Search, compare and understand digital solutions',
    searchThirdMainDescription: 'Implement',
    searchThirdSubDescription: 'Realize digital projects with trusted partners',
    supplyDigitalFirstMainDescription: 'Get inbound customer leads',
    supplyDigitalFirstSubDescription: 'That are qualified according to your specifications.',
    supplyDigitalSecondMainDescription: 'Contact the decision makers', // connect with
    supplyDigitalSecondSubDescription: 'To accelerate projects and deals.',
    supplyDigitalThirdMainDescription: 'Build reputation and trust',
    supplyDigitalThirdSubDescription: 'By leveraging your business network and references.',
    supplyDigitalForthMainDescription: 'Access your industry environment',
    supplyDigitalForthSubDescription: 'To lobby, collaborate and innovate.',
    howitWorksMainHeading: 'How it Works',
    howitWorksSubHeading1: 'Doing business with',
    howitWorksSubHeading2: 'perfect-match digital',
    howitWorksSubHeading3: '& strategic partners',
    howitWorksFirstDescription: 'Create your company profile and specify your objectives.',
    howitWorksSecondDescription: 'With a mix of market research, artificial intelligence, network and data technologies, we deliver …',
    howitWorksthirdDescription: '… solutions, partners or customers that perfectly match your business and objectives.',
    howitWorksfourthDescription: 'Contact trusted partners and start collaboration immediately.',
    howitWorksfifthDescription: 'Grow your business, innovate, digitalise and discover technology opportunities.',
    pricingSubHeading: 'Transparent, Fair, Value-added based.',
    pricingFirstDescriptionOne: 'Joining and using DigitalPartners.io is ',
    pricingFirstDescriptionTwo: ' of charge.',
    pricingSecondDescriptionOne: 'Premium-Service pricing is based on your individual needs and objectives.',
    pricingSecondDescriptionTwo: ' of charge.',
    pricingThirdDescriptionOne: 'We charge a ',
    pricingThirdDescriptionTwo: 'consulting fee ',
    pricingThirdDescriptionThree: 'only if you generate ',
    pricingThirdDescriptionFour: 'revenues ',
    pricingThirdDescriptionFive: 'or you ',
    pricingThirdDescriptionSix: 'begin a strategic project ',
    pricingThirdDescriptionSeven: 'resulting from our matches',
    pricingFourthDescriptionOne: 'We aim for perfect',
    pricingFourthDescriptionTwo: ' transparency ',
    pricingFourthDescriptionThree: 'Before any payment obligation arises, we will always ask you to opt in or out of the deal.',
    pricingFree: 'free ',
    demoButton: 'Schedule a demo',
    aboutusSubHeading: 'Who are we',
    positionCEO: 'Dedicated entrepreneur and technologist. Background in Finance & Banking. Loves economics and interdisciplinary collaboration. Surfing and kitesurfing enthusiast.',
    positionCTO: 'Passionate developer and system architect. Experience from international tech companies. Coding mentor. Hobby: building the world’s best cat image search.',
    loginNoAccount: 'Don\'t have an account yet? Sign Up',
    signupAlreadySignedUp: 'Already have an account? Log In',
    signupFirstName: 'First Name',
    signupLastName: 'Last Name',
    signupEmail: 'Company Email',
    signupPassword: 'Password',
    signupConfirmPassword: 'Confirm Password',
    signupForgetPassword: 'Forgot Password?',
    signUpSubmit: 'Proceed',
    sendButton: 'Send',
    submitButton: 'Submit',
    requiredFields: 'Required',
    footerContact: 'Contact',
    footerImprint: 'Imprint',
    footerAboutUs: 'Jobs',
    footerLegal: 'Legal',
    recover: 'Recover your Password',
    signupFourCharacters: 'Must be atleast 4 characters',
    signupSixCharacters: 'Must be atleast 6 characters',
    signupFiftheenCharacters: 'Must be less than 15 characters',
    signupCompany: 'Company Name',
    invalidEmail: 'Invalid Email domain',
    mismatchPassword: 'Passwords do not match',
    emailConfirmed: 'Email Confirmed! Log in',
    resetPassword: 'Reset your Password',
    webAppNav1: 'Company',
    webAppNav2: 'Search',
    webAppNav3: 'Matches',
    webAppNav4: 'Settings',
    webAppNav5: 'Projects',
    webAppNav6: 'News',
    edit: 'edit',
    publish: 'publish',
    unpublish: 'unpublish',
    save: 'Save',
    cancel: 'cancel',
    inviteTeam: 'Invite Team Members',
    invitePartners: 'Invite Partners',
    imprint: 'Imprint',
    legal: 'Legal',
    delelteAccount: 'Delete Account',
    logout: 'Log Out',
    newsletterNo: 'You are not subscribed to the Newsletter',
    newsLetterYes: 'You are subscribed to the Newsletter',
    signupThanks: 'Thank you for registering at digitalpartners.io',
    signupConfirmEmail: 'Check your inbox! We have sent you a confirmation email!',
    notifiyConfirm: 'Please Confirm your Email',
    contactHeading: 'Contact - Imprint',
    contactFormName: 'Name',
    contactFromPhone: 'Phone Nr.',
    contactFormEmail: 'Email',
    contactFormSubject: 'Subject',
    contactFormMessage: 'Message',
    contactFromSend: 'Send',
    inviteMessage: 'Your personal message',
    inviteCompanyName: 'Company Name',
    matchesName: 'Save Match',
    matchIndustry: 'Industry',
    matchHeadquarters: 'Headquarters',
    matchbusinessType: 'Business Type',
    matchProductCategory: 'Product Category',
    matchValueProposition: 'Value Proposition',
    matchUniqueSellingPoint: 'Unique Selling Points',
    matchdescription: 'Description',
    searchPreferences: 'New Search',
    productSearch: 'Products/Services - Take into account my company profile',
    productDetailSearch: 'Products/Services - Do not take into account my company profile',
    partnerSearch: 'Partners - Take into account my company profile',
    partnerDetailSearch: 'Partners - Do not take into account my company profile',
    projectDetailSearch: 'Projects - Search and apply to project requests',
    searchButton: 'Search',
    searchDelete: 'Delete',
    searchingProducts: 'Searching for products/services',
    searchingPartners: 'Searching for strategic partners',
    profileupdateNotify: 'Profile Updated Successfully',
    searchConfirmDelete: 'Are you sure you want to delete this saved search?',
    accountdeleteNotify: 'Are you sure you want to delete your account?',
    settingsNotify: 'Settings Updated Successfully',
    saveMatchButton: 'Save Match',
    contactButton: 'Contact',
    deleteButton: 'Delete',
    saveMatchNotify: 'Match saved successfully',
    searchNotify: 'New search saved successfully',
    matchNoSearch: 'You have not performed any search. As soon as you submit a search, all matches result will be shown here.',
    passwordSaveNotify: 'Password Updated Successfully',
    matchNoResult: 'We have not found any matches for your search request. You will be notified, as soon as we find suitable matches.',
    matchNoResult2: 'You may also adapt your search to find immediate results.',
    matchProgress: 'We are currently matching your request. The careful curation your results may take a moment. You will be informed via Email as soon as your results are available here.',
    reachOut: 'Reach out at any time!',
    phoneReach: ': +49 176 982 440 76',
    productName: 'Name is required',
    taxID: 'Tax-Identification Number according to § 27a UStG',
    toBe: ' (to be issued)',
    court: 'Court',
    tradeRegNum: 'Trade registry number',
    ManageD: 'Managing Directors',
    imprintPhone: 'Phone',
    Blog: 'Blog',
    /* Profile Page Start */
    productService: 'Product/Service',
    applicationDomain: 'Application Domain',
    valuePrice: 'Value & Price',
    operationDetails: 'Operation Details',
    addProductOrService: 'ADD A NEW PRODUCT OR SERVICE',
    removeProductOrService: 'REMOVE THIS PRODUCT OR SERVICE',
    addReference: 'ADD A NEW REFERENCE',
    removeReference: 'REMOVE REFERENCE',
    /* Logo Component */
    chooseFile: 'Choose file',
    changeFile: 'Change file',
    uploadFile: 'Upload your companies logo',
    cropFile: 'Company profile logo',
    viewFull: 'View Full',
    closeButton: 'Close',
    applyButton: 'Apply',
    removeSearch: 'Remove this search',
    /* Project Page */
    addProject: 'ADD A NEW PROJECT REQUEST',
    skipBotton: 'Skip',
    acceptButton: 'Accept',
    viewFullCompany: 'View Company',
    viewFullProject: 'View Project',
    viewFullApplication: 'View Full Application',
    withdraw: 'Withdraw',
    submitBotton: 'Submit',
    saveButton: 'Save',
    dateApplied: 'Date Applied',
    applyMoreProjectsOne: 'Create a',
    applyMoreProjectsTwo: ' project search',
    applyMoreProjectsThree: '',
    /* Application Cards */
    receivedApplication: 'Received Applications',
    skippedApplications: 'Skipped Applications',
    acceptedApplications: 'Accepted Applications',
    submittedApplications: 'Submitted Applications',
    successfulApplications: 'Successful Applications',
    rejectedApplications: 'Rejected Applications',
    inProgressApplications: 'In Progress Applications',
    projectCompanySector: 'Sector',
    application: 'Application',
    /* Application Section Labels */
    solution: 'Solution',
    ourPartners: 'Our Partners:',
    delete: 'Delete',
    appTechRecommendation: 'Technology recommendation',
    appPricingIndication: 'Pricing Indication(EUR)',
    appTimeLineIndication: 'Timeline Indication',
    appReferencesExperience: 'References /Experience',
    withdrawApplication: 'Withdraw Application',
    projectupdateNotify: 'Project Updated Successfully',
    removeProject: ' REMOVE THIS PROJECT',
    allApplication: 'My Applications',
    role: 'Account Type',
    phone: 'Phone Number',
    startupSearch: 'Search Startups - To invest, acquire, collaborate',
    matchProductClass: 'PRODUCT CLASS',
    matchTechnologyField: 'TECHNOLOGY APPLICATION FIELD',
    matchProductCoreTech: 'CORE TECHNOLOGIES',
    matchinvestmentStage: 'INVESTMENT STAGE',
    centerButton: 'Start your project',
    projectLPfirst: 'Or get personal support to',
    projectLPSecond: 'ideate and define',
    projectLPThird: 'your next project',
    verifyMatchButton: 'Verify'
  },
  de: {
    headerSearch: 'Tech suchen',
    headerSupply: 'Tech anbieten',
    headerHowitWorks: 'So geht’s',
    headerPrice: 'Preise',
    headerAboutUs: 'Über uns',
    headerSignup: 'Registrieren',
    headerLogin: 'Anmelden',
    headingDescription: 'EMPOWERING TECHNOLOGY PARTNERSHIPS',
    secondHeadingDescription: 'We make digital technology accessible to any business, to build a more innovative, collaborative and sustainable economy together.',
    useCasesHeading: 'Use Cases',
    useCasesHeading1: 'What we do',
    useCasesCard1Header: 'IoT & Machine Learning',
    useCasesCard1Title: 'Predictive maintenance',
    useCasesCard1Body: 'Wir haben Technologie-Anbieter zusammengebracht, um ein Endnutzer-Gerät mit einer smarten Wartungslösung auszustatten. Das Konzept wird durch Sensorik, Machine Learning und eine intuitive Nutzeroberfläche realisiert.',
    useCasesCard2Header: 'Enterprise Software',
    useCasesCard2Title: 'Produktions-Planungs Software',
    useCasesCard2Body: 'Um die Produktionskapazität und die Effizienz eines Automobilzulieferers zu verbessern haben wir diverse Software Lösungen verglichen und ausgewählt, die die Produktionsplanung nachhaltig verbessern.',
    useCasesCard3Header: 'Virtual Reality',
    useCasesCard3Title: 'Emotionales Marketing & Vertrieb',
    useCasesCard3Body: 'Gemeinsam mit unserem Maschienenbau Kunden haben wir eine digitale Vertriebsstategie entwickelt. Diese baut auf ein überzeugendes Virtual Reality Erlebnis während der Produktdemonstration auf.',
    searchDigitalHeading: 'Digitale Lösungen suchen',
    searchDigitalSubHeading1: 'Wir',
    searchDigitalSubHeading2: 'suchen',
    searchDigitalSubHeading3: 'nach digitalen Lösungen',
    searchFirstMainDescription: 'Gehen Sie auf Ideen- und Methodensuche',
    searchFirstSubDescription: 'Um mit unseren Beratern digitale Strategien aufzubauen und Lösungs-Anforderungen zu definieren',
    searchSecondMainDescription: 'Finden Sie digitale Lösungen',
    searchSecondSubDescription: 'Die Ihr bestehendes Geschäftsmodell, Prozesse, Budget und Ziele berücksichtigen',
    searchThirdMainDescription: 'Setzen Sie komplexe Technologieprojekte einfach und schnell um',
    searchThirdSubDescription: 'Nutzen Sie unsere Netzwerk-, Transaktions- und Kollaborationshilfen',
    supplyDigitalHeading: 'Digitale Lösungen anbieten',
    supplyDigitalSubHeading1: 'Wir',
    supplyDigitalSubHeading2: 'bieten',
    supplyDigitalSubHeading3: 'digitale Lösungen an',
    supplyDigitalFirstMainDescription: 'Finden Sie Kunden und Strategische Partner',
    supplyDigitalFirstSubDescription: 'Die genau zu Ihrem Angebot passen',
    supplyDigitalSecondMainDescription: 'Direkter Kontakt zu den richtigen Entscheidern',
    supplyDigitalSecondSubDescription: 'Beschleunigt die Vorgespräche und Verhandlungen bis zum Vertragsschluss',
    supplyDigitalThirdMainDescription: 'Bauen Sie Reputation auf',
    supplyDigitalThirdSubDescription: 'Und erstellen Sie eine Vertrauensbasis durch sichtbare Empfehlungen',
    supplyDigitalForthMainDescription: 'Lobbying und Organisation',
    supplyDigitalForthSubDescription: 'Erlaubt Ihnen effiziente Kollaboration mit Industrie-Partnern, um politische Ziele zu erreichen',
    howitWorksMainHeading: 'Wie es funktioniert',
    howitWorksSubHeading: 'Projekte mit passenden ',
    howitWorksSubHeading1: 'Projekte mit',
    howitWorksSubHeading2: 'passenden',
    howitWorksSubHeading3: 'Technologie-Partnern umsetzen',
    howitWorksFirstDescription: 'Unternehmensprofil erstellen und Objektiven definieren',
    howitWorksSecondDescription: 'Wir finden mit Datenanalyse, Semantik, KI und händischer Markt-/Technologie-Analyse...',
    howitWorksthirdDescription: '... Lösungen bzw. Kunden, die perfekt auf Ihren Anwendungsfall zugeschnitten sind.',
    howitWorksfourthDescription: 'Durch direkten Kontakt zu Entscheidern Projekte schnell und effizient umsetzen',
    howitWorksfifthDescription: 'Schöpfen Sie ihr Innovations- und Wachstumspotenzial aus und entdecken Sie die Möglichkeiten digitaler Technologien',
    pricingSubHeading: 'Transparent, fair, erfolgsbasiert',
    pricingFirstDescriptionOne: 'Der Beitritt und die Nutzung von DigitalPartners.io ist ',
    pricingFirstDescriptionTwo: '.',
    pricingFirstDescription: 'Die Anmeldung auf DigitalPartners.io ist kostenfrei.',
    pricingSecondDescriptionOne: 'Premium-Service Preise basieren auf Ihren individuellen Bedürfnissen und Zielen.',
    pricingSecondDescription: 'Wir erheben nur dann eine Kommissionsgebühr, wenn ein Projekt mit Kunden oder strategischen Partnern zustande kommt.',
    pricingThirdDescription: 'Wir streben nach absoluter Transparenz. Bevor Zahlungspflichten entstehen, holen wir Ihre selbstverständlich Ihre Zustimmung ein.',
    pricingFree: 'kostenlos',
    demoButton: 'Demo Termin vereinbaren',
    aboutusSubHeading: '',
    positionCEO: 'Unternehmer und Technologe aus Überzeugung. Hintergrund in der Finanzbranche & Banking. Liebt interdisziplinäre Zusammenarbeit. Passionierter Surfer und Kitesurfer.',
    positionCTO: 'Begeisterter Entwickler und System-Architekt. Erfahrung von internationalen Tech-Konzernen. Code Mentor. Hobby: Erstellung der besten Katzenbilder-Suchmaschine.',
    loginNoAccount: 'Sie haben noch kein Konto? Jetzt Registrieren',
    signupAlreadySignedUp: 'Sie haben bereits ein Konto? Einloggen',
    signupFirstName: 'Vorname',
    signupLastName: 'Nachname',
    signupEmail: 'Email',
    signupPassword: 'Passwort',
    signupConfirmPassword: 'Passwort bestätigen',
    signupForgetPassword: 'Passwort vergessen?',
    signUpSubmit: 'Weiter',
    signupCompany: 'Firmenname',
    sendButton: 'Senden',
    requiredFields: 'Bitte eingeben',
    footerContact: 'Kontakt',
    footerImprint: 'Impressum',
    footerAboutUs: 'Jobs',
    footerLegal: 'Legal',
    recover: 'Passwort wiederherstellen',
    signupFourCharacters: 'Mindestens 4 Zeichen',
    signupSixCharacters: 'Mindestens 6 Zeichen',
    signupFiftheenCharacters: 'Maximal 15 Zeichen',
    invalidEmail: 'Ungültige Email Domäne',
    mismatchPassword: 'Passworte stimmen nicht überein',
    emailConfirmed: 'Email Adresse bestätigt Anmelden',
    resetPassword: 'Passwort zurücksetzen',
    webAppNav1: 'Organisation',
    webAppNav2: 'Suchen',
    webAppNav3: 'Matches',
    webAppNav4: 'Einstellungen',
    edit: 'Bearbeiten',
    save: 'Speichern',
    cancel: 'ABBRECHEN',
    inviteTeam: 'Team einladen',
    invitePartners: 'Partner einladen',
    imprint: 'Impressum',
    legal: 'AGB',
    delelteAccount: 'Abmelden',
    logout: 'Account löschen',
    newsletterYes: 'Sie sind für den Newsletter angemeldet.',
    newsLetterNo: 'Sie sind nicht für den Newsletter angemeldet.',
    signupThanks: 'Vielen Dank für Ihre Anmeldung!',
    signupConfirmEmail: 'Wir haben Ihnen eine Email mit Bestätigungslink gesendet!',
    notifiyConfirm: 'Bitte bestätigen Sie Ihre Email-Adresse!',
    contactHeading: 'Kontakt - Impressum',
    contactFormName: 'Name',
    contactFromPhone: 'Telefon Nr.',
    contactFormEmail: 'Email',
    contactFormSubject: 'Betreff',
    contactFormMessage: 'Nachricht',
    contactFromSend: 'Abschicken',
    inviteMessage: 'Ihre persönliche Nachricht',
    inviteCompanyName: 'Firmenname',
    matchesName: 'Save Match',
    matchIndustry: 'Industrie',
    matchHeadquarters: 'Hauptsitz',
    matchbusinessType: 'Geschäftsart',
    matchProductCategory: 'Produktkategorie',
    matchValueProposition: 'Werteproposition',
    matchUniqueSellingPoint: 'Alleinstellungsmerkmale',
    matchdescription: 'Beschreibung',
    searchPreferences: 'New Search',
    productSearch: 'Produkte/Services – Mein Firmenprofil berücksichtigen',
    productDetailSearch: 'Produkte/Services – Mein Firmenprofil nicht berücksichtigen',
    partnerSearch: 'Partner Unternehmen – Mein Firmenprofil berücksichtigen',
    partnerDetailSearch: 'Partner Unternehmen – Mein Firmenprofile nicht berücksichtigen',
    projectDetailSearch: 'Projekte – Projekt-Inserate suchen und bewerben',
    searchButton: 'Suchen',
    searchDelete: 'Löschen',
    searchingProducts: 'Produkt/Service Suche',
    searchingPartners: 'Unternehmen Suche',
    profileupdateNotify: 'Profiländerungen gespeichert',
    searchConfirmDelete: 'Sind Sie sicher, dass sie diese Suche löschen wollen?',
    accountdeleteNotify: 'Möchten Sie Ihren Account unwiderruflich löschen?',
    settingsNotify: 'Einstellungen geändert',
    saveMatchButton: 'Speichern',
    searchNotify: 'Suchanfrage erstellt!',
    contactButton: 'Kontakt',
    saveMatchNotify: 'Match gespeichert',
    matchNoSearch: 'Sie haben noch keine Suche durchgeführt. Sobald Sie eine Suchanfrage aufgeben, werden alle Matches hier angezeit',
    passwordSaveNotify: 'Passwort geändert',
    matchNoResult: 'Es gibt leider keine Matches für Ihre Suchanfrage. Sie werden benachrichtigt, sobald wir passende Unternehmen für Sie gefunden haben.',
    matchNoResult2: '',
    matchProgress: 'Wir suchen derzeit nach passenden Ergebnissen. Das kuratieren kann etwas Zeit in Anspruch nehmen. Sie erhalten eine Email, sobald Ihre Ergebnisse Verfügbar sind.“',
    reachOut: 'Rufen Sie uns jederzeit an!',
    productName: 'Name ist erforderlich',
    taxID: 'Umsatzsteuer-Identifikationsnummer gem. § 27a UStG',
    toBe: ' (ausstehend)',
    court: 'Registergericht',
    tradeRegNum: 'Registernummer',
    ManageD: 'Vertretungsberechtigte Geschäftsführer',
    imprintPhone: 'Telefon',
    /* Profile Page Start */
    productService: 'Produkt/Service',
    applicationDomain: 'Anwendungsbereiche',
    valuePrice: 'Wert & Kosten',
    operationDetails: 'Operative Details',
    addProductOrService: 'PRODUKT/SERVICE HINZUFÜGEN',
    removeProductOrService: 'PRODUKT/SERVICE ENTFERNEN ENTFERNEN',
    addReference: 'REFERENZ HINZUFÜGEN',
    removeReference: 'REFERENZ ENTFERNEN',
    /* Logo Component */
    chooseFile: 'Choose file',
    changeFile: 'Change file',
    viewFull: 'Details',
    closeButton: 'Schließen',
    projectupdateNotify: 'Project gespeichert',
    publish: 'publish',
    unpublish: 'unpublish',
    ourPartners: 'Unsere Partner:',
    role: 'Account Type',
    phone: 'Phone Number',
    startupSearch: 'Search Startups - To invest, acquire, collaborate',
    matchProductClass: 'PRODUCT CLASS',
    matchTechnologyField: 'TECHNOLOGY APPLICATION FIELD',
    matchProductCoreTech: 'CORE TECHNOLOGIES',
    matchinvestmentStage: 'INVESTMENT STAGE',
    centerButton: 'Projekt starten',
    projectLPfirst: 'Oder',
    projectLPSecond: 'sprechen Sie persönlich mit uns',
    projectLPThird: 'um Ihre nächstes Projekt zu planen',
    verifyMatchButton: 'Verify'
  }
});

export default strings;
